/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ivan0
 */
public class Administrador extends javax.swing.JFrame {

    /**
     * Creates new form Administrador
     */
    public Administrador() {
        initComponents();
        
        this.setTitle("Eco-Woman");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        Perfil_cb_marca = new javax.swing.JComboBox<String>();
        Administrador_sp_huella = new javax.swing.JSpinner();
        Administrador_sp_costo = new javax.swing.JSpinner();
        Administrador_btn_regresar = new javax.swing.JButton();
        Administrador_img = new javax.swing.JLabel();
        Administrador_fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Administrador_btn_guardar.png"))); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 310, -1, -1));

        Perfil_cb_marca.setFont(new java.awt.Font("Century Gothic", 0, 10)); // NOI18N
        Perfil_cb_marca.setModel(new javax.swing.DefaultComboBoxModel<String>(new String[] { "Saba", "Kotex", "Naturella" }));
        jPanel1.add(Perfil_cb_marca, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, 190, -1));

        Administrador_sp_huella.setFont(new java.awt.Font("Century Gothic", 0, 10)); // NOI18N
        Administrador_sp_huella.setModel(new javax.swing.SpinnerNumberModel(0, 0, 100, 1));
        jPanel1.add(Administrador_sp_huella, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 170, 80, -1));

        Administrador_sp_costo.setFont(new java.awt.Font("Century Gothic", 0, 10)); // NOI18N
        Administrador_sp_costo.setModel(new javax.swing.SpinnerNumberModel(0, 0, 100, 1));
        jPanel1.add(Administrador_sp_costo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, 80, -1));

        Administrador_btn_regresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Adminstrador_btn_regresar.png"))); // NOI18N
        Administrador_btn_regresar.setBorderPainted(false);
        Administrador_btn_regresar.setContentAreaFilled(false);
        Administrador_btn_regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Administrador_btn_regresarActionPerformed(evt);
            }
        });
        jPanel1.add(Administrador_btn_regresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 90, 40, -1));

        Administrador_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Administrador_img.png"))); // NOI18N
        jPanel1.add(Administrador_img, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, -1, -1));

        Administrador_fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Administrador_fondo.png"))); // NOI18N
        jPanel1.add(Administrador_fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Administrador_btn_regresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Administrador_btn_regresarActionPerformed
        // TODO add your handling code here:
        Index index = new Index();
        index.setVisible(true);
        index.setLocationRelativeTo(null);
        
        this.setVisible(false);
    }//GEN-LAST:event_Administrador_btn_regresarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Administrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Administrador_btn_regresar;
    private javax.swing.JLabel Administrador_fondo;
    private javax.swing.JLabel Administrador_img;
    private javax.swing.JSpinner Administrador_sp_costo;
    private javax.swing.JSpinner Administrador_sp_huella;
    private javax.swing.JComboBox<String> Perfil_cb_marca;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
