/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ivan0
 */
public class Nosotros extends javax.swing.JPanel {

    /**
     * Creates new form Nosotros
     */
    public Nosotros() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Nosotros_fondo = new javax.swing.JLabel();
        Nosotros_img = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Nosotros_fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Nosotros_fondo.png"))); // NOI18N
        jPanel1.add(Nosotros_fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        Nosotros_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Nosotros_img.png"))); // NOI18N
        jPanel1.add(Nosotros_img, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, -1, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 480));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Nosotros_fondo;
    private javax.swing.JLabel Nosotros_img;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
